---
name: Test Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: [master]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Pyenv and Install Dependencies
        uses: gabrielfalcao/pyenv-action@v9
        with:
          default: 3.8.11
          command: |
            pip3 install -U pip wheel setuptools
            pip3 install -r requirements.txt
            pip3 install pytest
            pip3 install pytest-cov

      - name: Run Tests
        run: pytest test_plain.py --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

      - name: Publish Test Report/s
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/junit/*.xml'